[advisory]
id = "RUSTSEC-2020-0050"
package = "dync"
date = "2020-09-27"
informational = "unsound"
title = "VecCopy allows misaligned access to elements"
url = "https://github.com/elrnv/dync/issues/4"
description = """
`VecCopy::data` is created as a Vec of u8 but can be used to store and retrieve
elements of different types leading to misaligned access.
"""

[versions]
patched = []
