[advisory]
id = "RUSTSEC-2020-0042"
package = "stack"
date = "2020-09-24"
title = "Missing check in ArrayVec leads to out-of-bounds write."
url = "https://github.com/arcnmx/stack-rs/issues/4"
description = """
ArrayVec::insert allows insertion of an element into the array object into the
specified index. Due to a missing check on the upperbound of this index, it is
possible to write out of bounds.
"""

[versions]
patched = [">= 0.3.1"]
