[advisory]
id = "RUSTSEC-2018-0019"
package = "actix-web"
date = "2018-06-08"
title = "Multiple memory safety issues"
url = "https://github.com/actix/actix-web/issues/289"
categories = ["memory-corruption"]
description = """
Affected versions contain multiple memory safety issues, such as:

 - Unsoundly coercing immutable references to mutable references
 - Unsoundly extending lifetimes of strings
 - Adding the `Send` marker trait to objects that cannot be safely sent between threads

This may result in a variety of memory corruption scenarios, most likely use-after-free.
 
A signficant refactoring effort has been conducted to resolve these issues.
"""

[versions]
patched = [">= 0.7.15"]
