[advisory]
id = "RUSTSEC-0000-0000"
package = "array-queue"
date = "2020-09-26"
title = "array_queue pop_back() may cause a use-after-free"
url = "https://github.com/raviqqe/array-queue/issues/2"
description = """
array_queue implements a circular queue that wraps around an array. However, it
fails to properly index into the array in the `pop_back` function allowing the
reading of previously dropped or uninitialized memory.
"""
keywords = ["memory-corruption", "uninitialized-memory", "use-after-free"]

[affected]
functions = { "array-queue::ArrayQueue::push_back" = [">= 0.3.0"] }

[versions]

patched = []
unaffected = ["< 0.3.0"]
