[advisory]
id = "RUSTSEC-0000-0000"
package = "atom"
date = "2020-09-21"
informational = "unsound"
title = "Unsafe Send implementation in Atom allows data races"
url = "https://github.com/slide-rs/atom/issues/13"
description = """
The `atom` crate contains a security issue revolving around its implementation
of the Send trait. It incorrectly allows any arbitrary type to be sent across
threads potentially leading to use-after-free issues through memory races.
"""

[versions]
patched = []
