[advisory]
id = "RUSTSEC-0000-0000"
package = "ws"
date = "2019-09-25"
title = "Insufficient size checks in outgoing buffer in ws allows remote attacker to run the process out of memory"

url = "https://github.com/housleyjk/ws-rs/issues/291"

categories = ["denial-of-service"]
keywords = ["websocket", "dos", "ddos","oom", "memory", "remotely"]

description = """
Affected versions of this crate did not properly check and cap the growth of the outgoing buffer.

This allows a remote attacker to take down the process by growing the buffer of their (single) connection until the process runs out of memory it can allocate and is killed.

The flaw was corrected in the [`parity-ws` fork](https://crates.io/crates/parity-ws) (>0.10.0) by [disconnecting a client when the buffer runs full](https://github.com/housleyjk/ws-rs/pull/328).
"""

[versions]
patched = []
