[advisory]
id = "RUSTSEC-0000-0000"
package = "obstack"
date = "2020-09-03"
informational = "unsound"
title = "Obstack generates unaligned references"
url = "https://github.com/petertodd/rust-obstack/issues/4"
description = """
Obstack generates unaligned references for types that require a large alignment.
"""

[versions]
patched = [">= 0.1.4"]
